# Generated by Django 2.2.1 on 2020-02-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config", name="value", field=models.CharField(max_length=256),
        ),
    ]
