# Generated by Django 2.2.17 on 2021-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0005_auto_20210108_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
