# Generated by Django 2.2.4 on 2020-06-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoneyBall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hex_hash", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField()),
                ("json_file", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Upcoming",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hex_hash", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField()),
                ("json_file", models.FileField(upload_to="")),
            ],
        ),
    ]
