# Generated by Django 2.2.4 on 2020-06-17 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("moneyball", "0003_upcoming_last_run")]

    operations = [
        migrations.AddField(
            model_name="moneyball",
            name="crated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
