# Generated by Django 2.2.4 on 2020-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("moneyball", "0004_moneyball_crated")]

    operations = [
        migrations.AddField(
            model_name="moneyball",
            name="sport_key",
            field=models.CharField(default="", max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="moneyball",
            name="teams",
            field=models.CharField(default="", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="upcoming",
            name="sport_key",
            field=models.CharField(default="", max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="upcoming",
            name="teams",
            field=models.CharField(default="", max_length=64, null=True),
        ),
    ]
