# Generated by Django 2.2.4 on 2020-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("moneyball", "0005_auto_20200620_0951")]

    operations = [
        migrations.AddField(
            model_name="moneyball",
            name="result",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="moneyball",
            name="sport_key",
            field=models.CharField(default="", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="upcoming",
            name="sport_key",
            field=models.CharField(default="", max_length=32, null=True),
        ),
    ]
