# Generated by Django 2.2.4 on 2020-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("moneyball", "0006_auto_20200621_2132")]

    operations = [
        migrations.AlterField(
            model_name="moneyball",
            name="result",
            field=models.CharField(blank=True, default="-", max_length=8),
        )
    ]
