# Generated by Django 2.2.4 on 2020-07-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneyball", "0007_auto_20200621_2256"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moneyball",
            old_name="crated",
            new_name="created",
        ),
    ]
